"""
Generates app/analytics/data/seed.json - the demo jurisdiction tree and a
realistic complaint history for the analytics prototype.

Run:  python3 scripts/generate_analytics_seed.py [--copy-to <prototype analytics dir>]

Nothing in the output is a pre-computed metric. Each complaint is simulated
through the same rules the live escalation job enforces (resolve within the
category SLA, or breach -> escalate to the next level at the deadline), and
the analytics engine derives every number from those records at request time.

Times are stored as whole minutes relative to the moment the data is loaded
(negative = in the past, positive = in the future), so the demo never goes
stale: a complaint filed "3 days ago" is always 3 days old when the server
starts. The RNG is seeded, so the file is reproducible.
"""

import argparse
import json
import math
import os
import random
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from app.analytics.config import CATEGORY_SLA_DAYS, ESCALATION_CHAIN  # noqa: E402

DAY = 1440  # minutes
HORIZON_DAYS = 185
OUT = os.path.join(os.path.dirname(__file__), "..", "app", "analytics", "data", "seed.json")
SEED_JS_PREFIX = "/* Generated by citycare-backend/scripts/generate_analytics_seed.py - do not edit. */\nwindow.CC_SEED = "
SEED_JS_SUFFIX = ";\n"

# Existing Lucknow Sadar wards, copied verbatim from prototype/index.html so the
# government dashboard, the citizen geo-lock and the analytics all agree.
LUCKNOW_SADAR_WARDS = [
    ("ward24", "Ward 24 (Hazratganj)", "Ward 24", [26.850, 80.945],
     [[26.845, 80.930], [26.860, 80.932], [26.862, 80.955], [26.848, 80.958], [26.840, 80.942], [26.845, 80.930]]),
    ("ward42", "Ward 42 (Gomti Nagar)", "Ward 42", [26.858, 80.990],
     [[26.845, 80.970], [26.872, 80.972], [26.875, 81.012], [26.848, 81.010], [26.845, 80.970]]),
    ("ward17", "Ward 17 (Aliganj)", "Ward 17", [26.890, 80.948],
     [[26.875, 80.930], [26.905, 80.932], [26.908, 80.965], [26.878, 80.962], [26.875, 80.930]]),
    ("ward7", "Ward 7 (Chowk)", "Ward 7", [26.870, 80.908],
     [[26.855, 80.890], [26.885, 80.892], [26.888, 80.925], [26.858, 80.922], [26.855, 80.890]]),
    ("ward15", "Ward 15 (Indira Nagar)", "Ward 15", [26.890, 80.995],
     [[26.875, 80.972], [26.905, 80.975], [26.908, 81.015], [26.878, 81.012], [26.875, 80.972]]),
    ("ward30", "Ward 30 (Alambagh)", "Ward 30", [26.818, 80.915],
     [[26.800, 80.895], [26.835, 80.898], [26.838, 80.935], [26.805, 80.932], [26.800, 80.895]]),
]

# (state code, name, quality modifier, [(district code, name, [(sdm code, name, center, wards)])])
HIERARCHY = [
    ("UP", "Uttar Pradesh", 0.00, [
        ("LKO", "Lucknow", [
            ("SADAR", "Lucknow Sadar", (26.855, 80.950), "EXISTING"),
            ("MLG", "Mohanlalganj", (26.690, 80.980), [(51, "Nigohan"), (52, "Gosainganj"), (53, "Sisendi"), (54, "Mohanlalganj Bazaar")]),
            ("BKT", "Bakshi Ka Talab", (27.000, 80.930), [(61, "Itaunja"), (62, "Mahona"), (63, "Kathwara"), (64, "BKT Chauraha")]),
        ]),
        ("KNP", "Kanpur Nagar", [
            ("SADAR", "Kanpur Sadar", (26.460, 80.330), [(12, "Swaroop Nagar"), (33, "Kakadeo"), (8, "Civil Lines"), (41, "Govind Nagar"), (27, "Kidwai Nagar")]),
            ("BLH", "Bilhaur", (26.840, 80.070), [(3, "Bilhaur Town"), (5, "Shivrajpur"), (9, "Arual")]),
        ]),
        ("VNS", "Varanasi", [
            ("SADAR", "Varanasi Sadar", (25.320, 82.990), [(18, "Lanka"), (22, "Sigra"), (7, "Bhelupur"), (35, "Chetganj"), (29, "Lahurabir")]),
            ("PND", "Pindra", (25.480, 82.800), [(2, "Pindra"), (4, "Babatpur"), (6, "Phulpur")]),
        ]),
    ]),
    ("MH", "Maharashtra", 0.05, [
        ("PUN", "Pune", [
            ("HVL", "Haveli", (18.520, 73.860), [(11, "Kothrud"), (23, "Hadapsar"), (4, "Wagholi"), (16, "Kharadi"), (8, "Aundh")]),
            ("MVL", "Maval", (18.730, 73.680), [(2, "Talegaon"), (5, "Lonavala"), (7, "Vadgaon")]),
        ]),
        ("NGP", "Nagpur", [
            ("URB", "Nagpur Urban", (21.150, 79.090), [(14, "Dharampeth"), (19, "Sitabuldi"), (21, "Sadar"), (32, "Manish Nagar"), (26, "Wardhaman Nagar")]),
            ("KMP", "Kamptee", (21.220, 79.190), [(1, "Kamptee"), (3, "Koradi"), (6, "Mahadula")]),
        ]),
        ("MSD", "Mumbai Suburban", [
            ("AND", "Andheri", (19.120, 72.850), [(63, "Andheri East"), (66, "Andheri West"), (72, "Jogeshwari"), (81, "Vile Parle")]),
            ("BOR", "Borivali", (19.230, 72.860), [(9, "Borivali West"), (24, "Kandivali"), (35, "Malad"), (2, "Dahisar")]),
        ]),
    ]),
    ("KA", "Karnataka", 0.10, [
        ("BLR", "Bengaluru Urban", [
            ("NTH", "Bengaluru North", (13.040, 77.590), [(7, "Hebbal"), (4, "Yelahanka"), (9, "Jakkur"), (19, "RT Nagar"), (6, "Sahakara Nagar")]),
            ("STH", "Bengaluru South", (12.930, 77.580), [(169, "Jayanagar"), (177, "JP Nagar"), (176, "BTM Layout"), (163, "Banashankari"), (154, "Basavanagudi")]),
        ]),
        ("MYS", "Mysuru", [
            ("MYS", "Mysuru", (12.300, 76.640), [(12, "Chamundipuram"), (43, "Kuvempunagar"), (38, "Vijayanagar"), (21, "Saraswathipuram")]),
            ("NNJ", "Nanjangud", (12.120, 76.680), [(3, "Nanjangud Town"), (8, "Hullahalli"), (11, "Devarasanahalli")]),
        ]),
    ]),
    ("RJ", "Rajasthan", -0.12, [
        ("JPR", "Jaipur", [
            ("SNG", "Sanganer", (26.820, 75.790), [(31, "Malviya Nagar"), (44, "Mansarovar"), (57, "Sanganer Town"), (48, "Pratap Nagar")]),
            ("AMB", "Amber", (26.990, 75.850), [(2, "Amer"), (6, "Jaisinghpura"), (9, "Kunda")]),
        ]),
        ("JDH", "Jodhpur", [
            ("JDH", "Jodhpur", (26.280, 73.020), [(15, "Sardarpura"), (27, "Shastri Nagar"), (8, "Paota"), (33, "Ratanada")]),
            ("PHL", "Phalodi", (27.130, 72.360), [(1, "Phalodi Town"), (4, "Bap"), (7, "Lohawat")]),
        ]),
    ]),
    ("MP", "Madhya Pradesh", -0.07, [
        ("BPL", "Bhopal", [
            ("HUZ", "Huzur", (23.230, 77.410), [(52, "Arera Colony"), (35, "MP Nagar"), (80, "Kolar"), (47, "Shahpura")]),
            ("BRS", "Berasia", (23.630, 77.430), [(2, "Berasia Town"), (5, "Nazirabad"), (8, "Gunga")]),
        ]),
        ("IDR", "Indore", [
            ("IDR", "Indore", (22.720, 75.860), [(38, "Vijay Nagar"), (57, "Rajwada"), (43, "Palasia"), (72, "Bhawarkua"), (81, "Sudama Nagar")]),
            ("MHW", "Mhow", (22.550, 75.760), [(1, "Mhow Cantt"), (4, "Manpur"), (6, "Simrol")]),
        ]),
    ]),
]

CATEGORY_WEIGHTS = [
    ("roads", 14), ("garbage", 13), ("streetlights", 11), ("water", 11), ("drainage", 10),
    ("electricity", 8), ("sanitation", 7), ("infrastructure", 7), ("publicsafety", 5),
    ("traffic", 5), ("community", 4), ("environment", 3), ("crime", 2),
]
BASE_SEVERITY = {"roads": 3, "electricity": 4, "publicsafety": 4, "crime": 4, "water": 3, "drainage": 3}

TITLES = {
    "roads": ["Pothole on {s}", "Damaged road surface near {l}", "Road cave-in on {s}", "Broken speed breaker near {l}"],
    "streetlights": ["Street light not working on {s}", "Flickering street lights near {l}", "Dark stretch on {s}, lights missing"],
    "garbage": ["Garbage overflowing near {l}", "Waste not collected on {s}", "Dumping of waste near {l}"],
    "water": ["No water supply on {s}", "Water leakage near {l}", "Contaminated tap water on {s}"],
    "drainage": ["Blocked drain near {l}", "Overflowing sewer on {s}", "Waterlogging near {l}"],
    "electricity": ["Exposed live wire near {l}", "Frequent power cuts on {s}", "Transformer sparking near {l}"],
    "sanitation": ["Public toilet blocked near {l}", "Unclean community toilet on {s}", "No sweeping on {s} for a week"],
    "infrastructure": ["Broken footpath tiles on {s}", "Damaged boundary wall near {l}", "Collapsed bus shelter near {l}"],
    "environment": ["Fallen tree blocking {s}", "Open burning of waste near {l}", "Dust from construction site near {l}"],
    "publicsafety": ["Open manhole on {s}", "Stray cattle menace near {l}", "Unsafe scaffolding on {s}"],
    "traffic": ["Traffic signal not working near {l}", "Illegal parking blocking {s}", "Missing zebra crossing near {l}"],
    "community": ["Encroachment on park near {l}", "Late-night loudspeaker noise near {l}", "Community hall in disrepair on {s}"],
    "crime": ["Chain snatching reported near {l}", "Illegal liquor sale near {l}", "Vandalism of public property on {s}"],
}
LANDMARKS = ["the main market", "the bus stand", "the government school", "the temple", "the railway crossing",
             "the community park", "the hospital gate", "the metro station", "the police chowki", "the vegetable mandi",
             "the post office", "the water tank"]
STREETS = ["Station Road", "Mall Road", "Main Road", "Ring Road", "Link Road", "Gali No. 4", "Sector 2 lane",
           "Canal Road", "Old City Road", "College Road"]


def clamp(x, lo, hi):
    return max(lo, min(hi, x))


class Profile:
    """How one authority behaves when a complaint is in its hands."""

    def __init__(self, diligence, trend=0.0, speed=0.5, evidence=0.9, gaming=False):
        self.diligence = diligence
        self.trend = trend      # change in diligence across the horizon (improving > 0)
        self.speed = speed      # typical fraction of the SLA window used
        self.evidence = evidence
        self.gaming = gaming

    def diligence_at(self, start_min):
        progress = clamp(1 + start_min / (HORIZON_DAYS * DAY), 0, 1)  # 0 = oldest, 1 = now
        return clamp(self.diligence + self.trend * (progress - 0.5), 0.2, 0.97)

    def reaction(self, evidence):
        """(confirm probability, dispute probability) for the citizen's response."""
        if self.gaming:
            return (0.40, 0.22) if evidence else (0.18, 0.47)
        return (0.62, 0.05) if evidence else (0.45, 0.25)


def build_units(rng):
    units = [{"id": "IN", "type": "country", "name": "India", "short": "India", "parent": None, "center": [22.6, 79.2]}]
    authorities = [{"id": "pm-IN", "unit": "IN", "title": "Prime Minister · Central Government"}]
    profiles = {"IN": Profile(0.9, speed=0.5)}
    for s_code, s_name, s_mod, districts in HIERARCHY:
        s_lat = s_lng = 0
        s_n = 0
        units.append({"id": s_code, "type": "state", "name": s_name, "short": s_name, "parent": "IN", "center": None})
        authorities.append({"id": f"cm-{s_code}", "unit": s_code, "title": f"Chief Minister · {s_name}"})
        profiles[s_code] = Profile(clamp(0.84 + s_mod + rng.uniform(-0.05, 0.05), 0.5, 0.96), speed=rng.uniform(0.35, 0.55))
        for d_code, d_name, sdms in districts:
            d_id = f"{s_code}-{d_code}"
            d_mod = s_mod + rng.uniform(-0.05, 0.05)
            units.append({"id": d_id, "type": "district", "name": d_name, "short": d_name, "parent": s_code, "center": None})
            authorities.append({"id": f"dm-{d_id}", "unit": d_id, "title": f"District Magistrate · {d_name}"})
            profiles[d_id] = Profile(clamp(0.77 + d_mod + rng.uniform(-0.1, 0.1), 0.45, 0.95), speed=rng.uniform(0.35, 0.6))
            d_lat = d_lng = 0
            for sd_code, sd_name, center, wards in sdms:
                sd_id = f"{d_id}-{sd_code}"
                units.append({"id": sd_id, "type": "sdm", "name": sd_name, "short": sd_name, "parent": d_id, "center": list(center)})
                authorities.append({"id": f"sdm-{sd_id}", "unit": sd_id, "title": f"SDM · {sd_name}"})
                profiles[sd_id] = Profile(clamp(0.76 + d_mod + rng.uniform(-0.14, 0.14), 0.4, 0.95), speed=rng.uniform(0.3, 0.6))
                d_lat += center[0]
                d_lng += center[1]
                if wards == "EXISTING":
                    for wid, name, short, wcenter, poly in LUCKNOW_SADAR_WARDS:
                        units.append({"id": wid, "type": "ward", "name": name, "short": short, "parent": sd_id,
                                      "center": wcenter, "polygon": poly})
                        authorities.append({"id": f"wc-{wid}", "unit": wid, "title": f"Ward Councillor · {name}"})
                    continue
                for i, (num, locality) in enumerate(wards):
                    wid = f"{sd_id}-W{num}"
                    ang = 2 * math.pi * i / len(wards) + rng.uniform(-0.3, 0.3)
                    rad = rng.uniform(0.018, 0.04)
                    lat = round(center[0] + rad * math.sin(ang), 4)
                    lng = round(center[1] + rad * math.cos(ang), 4)
                    h, w = 0.008, 0.009
                    poly = [[round(lat - h, 4), round(lng - w, 4)], [round(lat + h, 4), round(lng - w, 4)],
                            [round(lat + h, 4), round(lng + w, 4)], [round(lat - h, 4), round(lng + w, 4)],
                            [round(lat - h, 4), round(lng - w, 4)]]
                    units.append({"id": wid, "type": "ward", "name": f"Ward {num} ({locality})", "short": f"Ward {num}",
                                  "parent": sd_id, "center": [lat, lng], "polygon": poly})
                    authorities.append({"id": f"wc-{wid}", "unit": wid, "title": f"Ward Councillor · Ward {num} ({locality})"})
            n = len(sdms)
            next(u for u in units if u["id"] == d_id)["center"] = [round(d_lat / n, 4), round(d_lng / n, 4)]
            s_lat += d_lat / n
            s_lng += d_lng / n
            s_n += 1
        next(u for u in units if u["id"] == s_code)["center"] = [round(s_lat / s_n, 4), round(s_lng / s_n, 4)]

    # Village Head: kept from the existing prototype's role list ("Local region"
    # = Wards 24, 42 and 17). Observes these wards; not part of the urban chain.
    units.append({"id": "UP-LKO-LOCAL", "type": "region", "name": "Local Region (Hazratganj · Gomti Nagar · Aliganj)",
                  "short": "Local Region", "parent": "UP-LKO-SADAR", "center": [26.866, 80.962],
                  "ward_ids": ["ward24", "ward42", "ward17"]})
    authorities.append({"id": "vh-UP-LKO-LOCAL", "unit": "UP-LKO-LOCAL", "title": "Village Head · Local Region"})

    # Ward profiles. Lucknow Sadar is hand-tuned so the demo tells a clear story.
    tuned = {
        "ward24": Profile(0.84, speed=0.42, evidence=0.93),
        "ward42": Profile(0.90, trend=0.05, speed=0.33, evidence=0.95),
        "ward17": Profile(0.73, speed=0.55, evidence=0.88),
        "ward7": Profile(0.52, speed=0.70, evidence=0.80),
        "ward15": Profile(0.60, trend=0.70, speed=0.50, evidence=0.90),       # improving fast
        "ward30": Profile(0.92, speed=0.10, evidence=0.22, gaming=True),      # closes fast, little evidence
    }
    by_id = {u["id"]: u for u in units}
    for u in units:
        if u["type"] != "ward":
            continue
        if u["id"] in tuned:
            profiles[u["id"]] = tuned[u["id"]]
            continue
        state = by_id[by_id[by_id[u["parent"]]["parent"]]["parent"]]
        s_mod = next(h[2] for h in HIERARCHY if h[0] == state["id"])
        trend = rng.choice([0, 0, 0, 0.3, -0.25])
        gaming = rng.random() < 0.05
        profiles[u["id"]] = Profile(
            clamp(rng.uniform(0.56, 0.95) + s_mod, 0.35, 0.96), trend=trend,
            speed=rng.uniform(0.12, 0.3) if gaming else rng.uniform(0.25, 0.65),
            evidence=rng.uniform(0.2, 0.4) if gaming else rng.uniform(0.75, 0.97), gaming=gaming)
    return units, authorities, profiles


def ancestor(units_by_id, ward_id, level):
    order = {"WARD": "ward", "SDM": "sdm", "DISTRICT": "district", "STATE": "state", "COUNTRY": "country"}
    u = units_by_id[ward_id]
    while u["type"] != order[level]:
        u = units_by_id[u["parent"]]
    return u["id"]


def open_status(level, start):
    elapsed = -start
    if level == "WARD":
        return "PENDING" if elapsed < 0.5 * DAY else "VERIFIED" if elapsed < 1.6 * DAY else "IN_PROGRESS"
    return "ESCALATED" if elapsed < 2 * DAY else "IN_PROGRESS"


def simulate(rng, created, category, ward_id, units_by_id, profiles):
    sla = CATEGORY_SLA_DAYS[category] * DAY
    assignments, resolution, confirmation, confirmation_at = [], 0, 0, 0
    reopened, level_idx, start, status = 0, 0, created, None
    while True:
        level = ESCALATION_CHAIN[level_idx]
        prof = profiles[ancestor(units_by_id, ward_id, level)]
        deadline = start + sla
        if rng.random() < prof.diligence_at(start):
            used = clamp(prof.speed * (0.35 + 1.3 * rng.random()), 0.03, 0.96)
            t_res = start + round(sla * used)
            if t_res > 0:
                assignments.append([level, start, None, None])
                status = open_status(level, start)
                break
            evidence = rng.random() < (0.95 if reopened else prof.evidence)
            confirm_p, dispute_p = prof.reaction(evidence)
            if reopened:
                dispute_p = 0.0
            r = rng.random()
            t_react = t_res + round(rng.uniform(0.3, 4.0) * DAY)
            if r < dispute_p and t_react <= 0:
                assignments.append([level, start, "REOPENED", t_react, [t_res, int(evidence)]])
                reopened = 1
                start = t_react
                continue
            assignments.append([level, start, "RESOLVED", t_res])
            resolution = [t_res, level, int(evidence)]
            if dispute_p <= r < dispute_p + confirm_p and t_react <= 0:
                confirmation, confirmation_at = 1, t_react
            status = "RESOLVED"
            break
        if deadline > 0 or level_idx == len(ESCALATION_CHAIN) - 1:
            assignments.append([level, start, None, None])
            status = open_status(level, start)
            break
        assignments.append([level, start, "ESCALATED", deadline])
        level_idx += 1
        start = deadline
    return assignments, resolution, confirmation, confirmation_at, reopened, status


def handcrafted():
    """The complaints already shown in prototype/index.html, expressed as lifecycle records
    that obey the category SLAs, plus a few that breach live during a demo."""
    d = DAY
    return [
        # id, category, title, ward, sev, up, flags, created, status, assignments, resolution, conf, conf_at, reopen
        ["CMP24001", "infrastructure", "Broken Footpath Tiles on MG Marg", "ward24", 3, 94, 1 | 2 | 4, -4 * d, "IN_PROGRESS",
         [["WARD", -4 * d, None, None]], 0, 0, 0, 0],
        ["CMP24002", "streetlights", "Street Light Not Working Near Begum Hazrat Mahal Park", "ward24", 2, 21, 1 | 2 | 4, -9 * d, "RESOLVED",
         [["WARD", -9 * d, "RESOLVED", -1 * d]], [-1 * d, "WARD", 1], 0, 0, 0],
        ["CMP11234", "roads", "Pothole on 5th Street", "ward42", 4, 127, 1 | 2, -6 * d, "IN_PROGRESS",
         [["WARD", -6 * d, None, None]], 0, 0, 0, 0],
        ["CMP11233", "streetlights", "Street Light Not Working", "ward42", 3, 64, 1 | 2, -9 * d, "IN_PROGRESS",
         [["WARD", -9 * d, None, None]], 0, 0, 0, 0],
        ["CMP11232", "garbage", "Garbage Overflowing", "ward42", 2, 31, 1 | 2, -3 * d, "VERIFIED",
         [["WARD", -3 * d, None, None]], 0, 0, 0, 0],
        ["CMP11229", "drainage", "Blocked Drain Near Market", "ward42", 4, 203, 1 | 2, -17 * d, "ESCALATED",
         [["WARD", -17 * d, "ESCALATED", -7 * d], ["SDM", -7 * d, None, None]], 0, 0, 0, 0],
        ["CMP11221", "water", "Water Leakage on Service Road", "ward17", 3, 18, 0, -2 * d, "PENDING",
         [["WARD", -2 * d, None, None]], 0, 0, 0, 0],
        ["CMP11219", "infrastructure", "Broken Footpath Tiles", "ward17", 2, 47, 1 | 2, -22 * d, "RESOLVED",
         [["WARD", -22 * d, "ESCALATED", -8 * d], ["SDM", -8 * d, "RESOLVED", -4 * d]], [-4 * d, "SDM", 1], 1, -3 * d, 0],
        ["CMP11305", "crime", "Illegal Dumping at Riverbank", "ward7", 4, 88, 1 | 2, -5 * d, "ESCALATED",
         [["WARD", -5 * d, "ESCALATED", -2 * d], ["SDM", -2 * d, None, None]], 0, 0, 0, 0],
        ["CMP11298", "electricity", "Exposed Live Wire Near School", "ward7", 5, 341, 1 | 2, -19 * d, "ESCALATED",
         [["WARD", -19 * d, "ESCALATED", -12 * d], ["SDM", -12 * d, "ESCALATED", -5 * d], ["DISTRICT", -5 * d, None, None]], 0, 0, 0, 0],
        # Live-demo complaints: their Ward SLA runs out a few minutes after the server starts,
        # so the auto-escalation job can be watched moving them to the SDM.
        ["CMP42090", "garbage", "Garbage Not Lifted Near Vipin Khand Market", "ward42", 3, 44, 1 | 2, -7 * d + 6, "IN_PROGRESS",
         [["WARD", -7 * d + 6, None, None]], 0, 0, 0, 0],
        ["CMP24090", "water", "Low Water Pressure on Ashok Marg", "ward24", 3, 37, 1 | 2, -7 * d + 15, "IN_PROGRESS",
         [["WARD", -7 * d + 15, None, None]], 0, 0, 0, 0],
    ]


DESCRIPTIONS = {
    "CMP24001": "The footpath tiles near my house on Mahatma Gandhi Marg are broken, causing elderly pedestrians to trip.",
    "CMP24002": "The street light next to the park gate has been off for over a week; the stretch is completely dark after 7 pm.",
    "CMP11234": "Large pothole causing vehicle damage and traffic issues near the main junction.",
    "CMP11233": "Three consecutive street lights have been non-functional for two weeks, making the lane unsafe at night.",
    "CMP11232": "Community bin has not been cleared in over a week and is overflowing onto the footpath.",
    "CMP11229": "Stagnant water from a blocked drain is creating a mosquito breeding risk outside the vegetable market.",
    "CMP11221": "Continuous leakage from an underground pipe is wasting water and damaging the road surface.",
    "CMP11219": "Several footpath tiles are cracked and raised, creating a tripping hazard for pedestrians.",
    "CMP11305": "Unknown persons are dumping construction waste at the riverbank late at night, blocking the walking path.",
    "CMP11298": "A low-hanging live wire near the school gate poses a serious safety hazard to children.",
    "CMP42090": "The garbage point near Vipin Khand market has not been cleared for a week and stray animals are scattering it.",
    "CMP24090": "Water pressure on Ashok Marg drops to a trickle every morning; residents are unable to fill overhead tanks.",
}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--copy-to", help="also copy the file into this directory (the prototype's analytics folder)")
    args = ap.parse_args()

    rng = random.Random(20260927)
    units, authorities, profiles = build_units(rng)
    units_by_id = {u["id"]: u for u in units}
    wards = [u for u in units if u["type"] == "ward"]
    cats, weights = zip(*CATEGORY_WEIGHTS)

    complaints = handcrafted()
    taken = {c[0] for c in complaints}
    serial = 30001
    for w in wards:
        volume = {"ward42": 34, "ward24": 30, "ward30": 28, "ward7": 28, "ward15": 36, "ward17": 26}.get(w["id"], rng.randint(18, 30))
        for _ in range(volume):
            created = -round(HORIZON_DAYS * DAY * (rng.random() ** 1.12)) - 30
            category = rng.choices(cats, weights)[0]
            template = rng.choice(TITLES[category])
            title = template.format(s=rng.choice(STREETS), l=rng.choice(LANDMARKS))
            title = title[0].upper() + title[1:]
            severity = clamp(BASE_SEVERITY.get(category, 2) + rng.choice([-1, 0, 0, 1]), 1, 5)
            upvotes = severity * rng.randint(1, 24)
            cv = rng.random() < 0.75
            gv = cv and rng.random() < 0.85 and created < -DAY
            asg, res, conf, conf_at, reop, status = simulate(rng, created, category, w["id"], units_by_id, profiles)
            while f"CMP{serial}" in taken:
                serial += 1
            cid = f"CMP{serial}"
            serial += 1
            complaints.append([cid, category, title, w["id"], severity, upvotes, (1 if cv else 0) | (2 if gv else 0),
                               created, status, asg, res, conf, conf_at, reop])

    data = {
        "schema": 1,
        "note": ("Demo dataset for the CivicConnect analytics prototype, generated by "
                 "scripts/generate_analytics_seed.py (seeded RNG, reproducible). Times are minutes relative "
                 "to the moment the data is loaded (negative = past). No metric is stored here - the analytics "
                 "engine derives everything from these complaint records."),
        "complaint_fields": ["id", "category", "title", "ward_id", "severity", "upvotes", "flags", "created",
                             "status", "assignments", "resolution", "confirmation", "confirmation_at", "reopen_count"],
        "flag_bits": {"community_verified": 1, "gov_verified": 2, "reported_by_demo_citizen": 4},
        "assignment_fields": ["level", "start", "outcome", "outcome_at", "[closed_at, evidence] when REOPENED"],
        "resolution_fields": ["at", "level", "evidence"],
        "units": units,
        "authorities": authorities,
        "descriptions": DESCRIPTIONS,
        "complaints": complaints,
    }
    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w") as f:
        json.dump(data, f, separators=(",", ":"))
    size = os.path.getsize(OUT)
    print(f"wrote {OUT}: {len(units)} units, {len(authorities)} authorities, {len(complaints)} complaints, {size/1024:.0f} KB")
    if args.copy_to:
        # A script (not a .json fetch) so the prototype also works when opened as a local file.
        os.makedirs(args.copy_to, exist_ok=True)
        with open(OUT) as f, open(os.path.join(args.copy_to, "seed.js"), "w") as js:
            js.write(SEED_JS_PREFIX + f.read() + SEED_JS_SUFFIX)
        print(f"wrote {os.path.join(args.copy_to, 'seed.js')}")


if __name__ == "__main__":
    main()
